### PR TITLE
Support for strict mode (TB 60 compat)

### PR DESCRIPTION
**Pull request by klemens**
Apparently thunderbird 60 executes the extension code using strict mode. While most of the code worked fine, there were a few problems that lead to errors under strict mode. Now everything works under strict mode.

I also added `"use strict";` to all js files and a commit to bump the version.

### CODE REVIEW

**Comment by krukai** [comment]
Thank you for your work!

Sadly, it seems that this add-on is no longer maintained by the developer. There hasn't been any activity since September 2015.
In the light of this, would you perhaps be willing to release your fork? You would be the savior of us all!

**Comment by klemens** [comment]
@krukai: There weren't any breaking changes in thunderbird or lightning that affected this add-on since 2015, so I think it is pretty reasonable to not push any updates. Let's just give Ingo some time.

**Comment by Freudentaumel** [comment]
Up to which version of Thunderbird does your custom add-on work, Klemens?

**Comment by klemens** [comment]
@Freudentaumel: The maxVersion is set to 60.* and I have tested the changes with 60.0. I have not tested the minVersion.

Do you have problems with the patched version?

**Comment by Freudentaumel** [comment]
@klemens
I have no problems with the patched version. I just want to know what the future holds for the add-on - whether it will still work with versions TB 61, 62 and so on. 

What does your reference to the minVersion mean?

**Comment by klemens** [comment]
> whether it will still work with versions TB 61, 62

Well, these versions don't exist yet, so it is hard to tell it they will be compatible. :wink: But the stable thunderbird 60 will probably be supported for around a year from now (see firefox esr schedule), so you probably don't need to worry.

> What does your reference to the minVersion mean?

The manifest currently claims that the add-on works with thunderbird 3 and above, but I only tested with the most recent (and only supported) version.

**Review by venthur — APPROVED** [review]

**Comment by venthur** [comment]
Thanks for looking into this and the PR, let's hope this gets merged.

Cheers!

**Comment by richard67** [comment]
Works perfectly here with Thunderbird 60.2.1.

**Comment by kallekruse** [comment]
@klemens ,  

> @krukai: There weren't any breaking changes in thunderbird or lightning that affected this add-on since 2015, so I think it is pretty reasonable to not push any updates. Let's just give Ingo some time.

I'd say: "Some time" is up ;) Would you be willing to release your fork as a Thunderbird add-on?

**Comment by klemens** [comment]
I wrote him an email to ask if he has seen this pull request and if he would like help maintaining the add-on. Let's wait until this weekend and if he has not responded until then, I'll see if I can release a fork.

**Comment by ingomueller-net** [comment]
Thank you so much @klemens for the MR and everybody else for looking into it. I'll do my best to release a new version with it.

Also, sorry for not being more responsive. My life has moved on and I am not using Thunderbird myself anymore for years. This makes it hard to motivate myself to do anything. But I see that at least this maintenance is absolutely required. Hopefully, with this fix, it will continue to work for a while more ;)

**Comment by ingomueller-net** [comment]
OK, the new version is waiting for review: https://addons.thunderbird.net/en-US/developers/addon/thunderbirthday/versions/2468767.

**Comment by myrdd** [comment]
> https://addons.thunderbird.net/en-US/developers/addon/thunderbirthday/versions/2468767

that's the developer link. the url for users is
https://addons.thunderbird.net/en-US/thunderbird/addon/thunderbirthday/versions/0.8.3

**Pull request merged**
